services:
  trainer-service:
    build: ./trainer-service
    container_name: naive-bayes-trainer
    ports:
      - "8001:8001"
    networks:
      - naive-bayes-network

  classifier-service:
    build: ./classifier-service
    container_name: naive-bayes-classifier
    ports:
      - "8000:8000"
    depends_on:
      - trainer-service
    networks:
      - naive-bayes-network
    environment:
      - TRAINER_SERVICE_URL=http://trainer-service:8001

networks:
  naive-bayes-network:
    driver: bridge
